#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum MachineStatus {
    Running,
    Stopped,
    Suspended,
    Error,
}

impl MachineStatus {
    pub(super) const fn label(self) -> &'static str {
        match self {
            Self::Running => "Running",
            Self::Stopped => "Stopped",
            Self::Suspended => "Suspended",
            Self::Error => "Error",
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub(super) struct MachineSummary {
    pub(super) name: &'static str,
    pub(super) operating_system: &'static str,
    pub(super) os_mark: &'static str,
    pub(super) status: MachineStatus,
    pub(super) cpu_label: &'static str,
    pub(super) cpu_fill: f32,
    pub(super) memory_label: &'static str,
    pub(super) memory_fill: f32,
    pub(super) ip_address: &'static str,
    pub(super) uptime: &'static str,
    pub(super) starred: bool,
}

pub(super) const SAMPLE_MACHINES: [MachineSummary; 0] = [
    // MachineSummary {
    //     name: "prod-web-01",
    //     operating_system: "Ubuntu 24.04",
    //     os_mark: "U",
    //     status: MachineStatus::Running,
    //     cpu_label: "6%",
    //     cpu_fill: 31.,
    //     memory_label: "6.2 / 8 GB",
    //     memory_fill: 63.,
    //     ip_address: "192.168.1.101",
    //     uptime: "4d 11h",
    //     starred: true,
    // },
    // MachineSummary {
    //     name: "prod-db-primary",
    //     operating_system: "Debian 12",
    //     os_mark: "D",
    //     status: MachineStatus::Running,
    //     cpu_label: "34%",
    //     cpu_fill: 45.,
    //     memory_label: "14.1 / 16 GB",
    //     memory_fill: 72.,
    //     ip_address: "192.168.1.102",
    //     uptime: "21d 6h",
    //     starred: true,
    // },
    // MachineSummary {
    //     name: "prod-lb",
    //     operating_system: "Alpine Linux 3.19",
    //     os_mark: "A",
    //     status: MachineStatus::Running,
    //     cpu_label: "12%",
    //     cpu_fill: 36.,
    //     memory_label: "0.4 / 1 GB",
    //     memory_fill: 29.,
    //     ip_address: "192.168.1.100",
    //     uptime: "21d 6h",
    //     starred: false,
    // },
    // MachineSummary {
    //     name: "staging-api",
    //     operating_system: "Ubuntu 22.04",
    //     os_mark: "U",
    //     status: MachineStatus::Running,
    //     cpu_label: "12%",
    //     cpu_fill: 36.,
    //     memory_label: "3.8 / 8 GB",
    //     memory_fill: 51.,
    //     ip_address: "10.0.1.10",
    //     uptime: "8d 2h",
    //     starred: false,
    // },
    // MachineSummary {
    //     name: "staging-db",
    //     operating_system: "Debian 12",
    //     os_mark: "D",
    //     status: MachineStatus::Running,
    //     cpu_label: "5%",
    //     cpu_fill: 22.,
    //     memory_label: "5.1 / 8 GB",
    //     memory_fill: 57.,
    //     ip_address: "10.0.1.11",
    //     uptime: "8d 1h",
    //     starred: false,
    // },
    // MachineSummary {
    //     name: "dev-sandbox",
    //     operating_system: "Fedora 40",
    //     os_mark: "F",
    //     status: MachineStatus::Stopped,
    //     cpu_label: "—",
    //     cpu_fill: 0.,
    //     memory_label: "—",
    //     memory_fill: 0.,
    //     ip_address: "—",
    //     uptime: "—",
    //     starred: false,
    // },
    // MachineSummary {
    //     name: "dev-k8s-01",
    //     operating_system: "Alpine Linux 3.19",
    //     os_mark: "A",
    //     status: MachineStatus::Running,
    //     cpu_label: "88%",
    //     cpu_fill: 70.,
    //     memory_label: "1.7 / 2 GB",
    //     memory_fill: 68.,
    //     ip_address: "10.0.2.11",
    //     uptime: "3d 4h",
    //     starred: false,
    // },
    // MachineSummary {
    //     name: "dev-k8s-02",
    //     operating_system: "Alpine Linux 3.19",
    //     os_mark: "A",
    //     status: MachineStatus::Error,
    //     cpu_label: "91%",
    //     cpu_fill: 72.,
    //     memory_label: "1.9 / 2 GB",
    //     memory_fill: 76.,
    //     ip_address: "10.0.2.12",
    //     uptime: "—",
    //     starred: false,
    // },
    // MachineSummary {
    //     name: "win-test-env",
    //     operating_system: "Windows Server 2022",
    //     os_mark: "W",
    //     status: MachineStatus::Suspended,
    //     cpu_label: "—",
    //     cpu_fill: 0.,
    //     memory_label: "—",
    //     memory_fill: 0.,
    //     ip_address: "—",
    //     uptime: "—",
    //     starred: false,
    // },
    // MachineSummary {
    //     name: "backup-runner",
    //     operating_system: "Debian 12",
    //     os_mark: "D",
    //     status: MachineStatus::Running,
    //     cpu_label: "5%",
    //     cpu_fill: 22.,
    //     memory_label: "0.9 / 4 GB",
    //     memory_fill: 38.,
    //     ip_address: "192.168.1.108",
    //     uptime: "67d 1h",
    //     starred: false,
    // },
    // MachineSummary {
    //     name: "vpn-gateway",
    //     operating_system: "Ubuntu 22.04",
    //     os_mark: "U",
    //     status: MachineStatus::Running,
    //     cpu_label: "3%",
    //     cpu_fill: 20.,
    //     memory_label: "0.4 / 1 GB",
    //     memory_fill: 28.,
    //     ip_address: "192.168.1.109",
    //     uptime: "12d 3h",
    //     starred: false,
    // },
    // MachineSummary {
    //     name: "macos-ci",
    //     operating_system: "macOS Sonoma",
    //     os_mark: "M",
    //     status: MachineStatus::Stopped,
    //     cpu_label: "—",
    //     cpu_fill: 0.,
    //     memory_label: "—",
    //     memory_fill: 0.,
    //     ip_address: "—",
    //     uptime: "—",
    //     starred: false,
    // },
];
