[package]
name = "virt-desk"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
directories = "6.0.0"
gpui-kit = "0.7"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-error = "0.2.1"
tracing-subscriber = {version = "0.3.23", features = ["env-filter"]}


[profile.release]
codegen-units = 1
lto = true

[profile.dev]
opt-level = 1


[profile.dev.package]
gpui-pre = { opt-level = 3 }
gpui-component = { opt-level = 3 }
gpui-kit = { opt-level = 3 }
gpui-kit-assets = { opt-level = 3 }
gpui-pre-macros = { opt-level = 3 }
gpui-pre-platform = { opt-level = 3 }
rustybuzz = { opt-level = 3 }
taffy = { opt-level = 3 }
ttf-parser = { opt-level = 3 }


#[lints.clippy]
#pedantic = { level = "deny", priority = -1 }
#nursery = { level = "deny", priority = -1 }
#
#unwrap_used = "warn"
#expect_used = "warn"
#indexing_slicing = "warn"
#arithmetic_side_effects = "warn"
#string_slice = "warn"
#panic_in_result_fn = "warn"
#
#panic = "warn"
#todo = "warn"
#unimplemented = "warn"
#unreachable = "warn"
#as_conversions = "warn"
